name: Doxygen GitHub Pages Deploy Action for MB-System

on:
  push:
    branches:
      - feature-newgui

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: qt-documentation
          config_file: qt-documentation/doxyfile-xxxyyyzzz
